## Sustainable Multimodal Mobility Network Dataset

## 1. Dataset Overview

This notebook creates a connected transportation network dataset for the
AI-Powered Sustainable Multimodal Route Planner.

The dataset represents connections between locations and provides transportation
options such as Walking, Bicycle, Public Transport, and Car.

Each connection contains information about distance, travel time, cost, and CO₂
emissions. The resulting dataset will be used to generate and evaluate
multimodal journeys based on user-defined time and budget constraints.

In [30]:
import pandas as pd
import numpy as np

In [31]:
df1 = pd.DataFrame({
    "connection_id": [
        "C001", "C001", "C001", "C001",
        "C002", "C002", "C002", "C002",
        "C003", "C003", "C003", "C003",
        "C004", "C004", "C004", "C004",
        "C005", "C005", "C005", "C005"
    ],
    "source": [
        "Koti", "Koti", "Koti", "Koti",
        "Koti", "Koti", "Koti", "Koti",
        "Koti", "Koti", "Koti", "Koti",
        "Abids", "Abids", "Abids", "Abids",
        "Abids", "Abids", "Abids", "Abids"
    ],
    "destination": [
        "Abids", "Abids", "Abids", "Abids",
        "Nampally", "Nampally", "Nampally", "Nampally",
        "Charminar", "Charminar", "Charminar", "Charminar",
        "Nampally", "Nampally", "Nampally", "Nampally",
        "Charminar", "Charminar", "Charminar", "Charminar"
    ],
    "mode": [
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car"
    ],
    "distance_km": [
        2.0, 2.0, 2.0, 2.0,
        3.0, 3.0, 3.0, 3.0,
        4.0, 4.0, 4.0, 4.0,
        1.5, 1.5, 1.5, 1.5,
        3.0, 3.0, 3.0, 3.0
    ],
    "duration_min": [
        26, 9, 16, 8,
        38, 13, 22, 11,
        50, 17, 28, 14,
        19, 7, 12, 6,
        38, 13, 22, 11
    ],
    "cost_inr": [
        0, 0, 15, 35,
        0, 0, 15, 45,
        0, 0, 20, 65,
        0, 0, 15, 30,
        0, 0, 15, 45
    ],
    "co2_kg": [
        0.0, 0.0, 0.2, 0.5,
        0.0, 0.0, 0.3, 0.7,
        0.0, 0.0, 0.4, 0.9,
        0.0, 0.0, 0.2, 0.4,
        0.0, 0.0, 0.3, 0.7
    ]
})

df1

,connection_id,source,destination,mode,distance_km,duration_min,cost_inr,co2_kg
0,C001,Koti,Abids,Walking,2.0,26,0,0.0
1,C001,Koti,Abids,Bicycle,2.0,9,0,0.0
2,C001,Koti,Abids,Public Transport,2.0,16,15,0.2
3,C001,Koti,Abids,Car,2.0,8,35,0.5
4,C002,Koti,Nampally,Walking,3.0,38,0,0.0
5,C002,Koti,Nampally,Bicycle,3.0,13,0,0.0
6,C002,Koti,Nampally,Public Transport,3.0,22,15,0.3
7,C002,Koti,Nampally,Car,3.0,11,45,0.7
8,C003,Koti,Charminar,Walking,4.0,50,0,0.0
9,C003,Koti,Charminar,Bicycle,4.0,17,0,0.0
10,C003,Koti,Charminar,Public Transport,4.0,28,20,0.4
11,C003,Koti,Charminar,Car,4.0,14,65,0.9
12,C004,Abids,Nampally,Walking,1.5,19,0,0.0
13,C004,Abids,Nampally,Bicycle,1.5,7,0,0.0
14,C004,Abids,Nampally,Public Transport,1.5,12,15,0.2
15,C004,Abids,Nampally,Car,1.5,6,30,0.4
16,C005,Abids,Charminar,Walking,3.0,38,0,0.0
17,C005,Abids,Charminar,Bicycle,3.0,13,0,0.0
18,C005,Abids,Charminar,Public Transport,3.0,22,15,0.3
19,C005,Abids,Charminar,Car,3.0,11,45,0.7

In [32]:
print('Shape: ',df1.shape)

Shape:  (20, 8)

In [33]:
print('Unique Connections: ',df1['connection_id'].nunique())

Unique Connections:  5

In [34]:
df2 = pd.DataFrame({
    "connection_id": [
        "C006", "C006", "C006", "C006",
        "C007", "C007", "C007", "C007",
        "C008", "C008", "C008", "C008",
        "C009", "C009", "C009", "C009",
        "C010", "C010", "C010", "C010"
    ],
    "source": [
        "Nampally", "Nampally", "Nampally", "Nampally",
        "Nampally", "Nampally", "Nampally", "Nampally",
        "Mehdipatnam", "Mehdipatnam", "Mehdipatnam", "Mehdipatnam",
        "Mehdipatnam", "Mehdipatnam", "Mehdipatnam", "Mehdipatnam",
        "Ameerpet", "Ameerpet", "Ameerpet", "Ameerpet"
    ],
    "destination": [
        "Mehdipatnam", "Mehdipatnam", "Mehdipatnam", "Mehdipatnam",
        "Ameerpet", "Ameerpet", "Ameerpet", "Ameerpet",
        "Charminar", "Charminar", "Charminar", "Charminar",
        "Banjara Hills", "Banjara Hills", "Banjara Hills", "Banjara Hills",
        "Begumpet", "Begumpet", "Begumpet", "Begumpet"
    ],
    "mode": [
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car"
    ],
    "distance_km": [
        5.0, 5.0, 5.0, 5.0,
        4.0, 4.0, 4.0, 4.0,
        6.0, 6.0, 6.0, 6.0,
        4.0, 4.0, 4.0, 4.0,
        3.5, 3.5, 3.5, 3.5
    ],
    "duration_min": [
        64, 22, 35, 18,
        50, 17, 28, 13,
        76, 25, 42, 21,
        51, 17, 30, 15,
        44, 15, 25, 12
    ],
    "cost_inr": [
        0, 0, 20, 70,
        0, 0, 20, 60,
        0, 0, 25, 90,
        0, 0, 20, 70,
        0, 0, 15, 55
    ],
    "co2_kg": [
        0.0, 0.0, 0.5, 1.0,
        0.0, 0.0, 0.4, 0.8,
        0.0, 0.0, 0.6, 1.2,
        0.0, 0.0, 0.4, 0.8,
        0.0, 0.0, 0.3, 0.6
    ]
})

df2

,connection_id,source,destination,mode,distance_km,duration_min,cost_inr,co2_kg
0,C006,Nampally,Mehdipatnam,Walking,5.0,64,0,0.0
1,C006,Nampally,Mehdipatnam,Bicycle,5.0,22,0,0.0
2,C006,Nampally,Mehdipatnam,Public Transport,5.0,35,20,0.5
3,C006,Nampally,Mehdipatnam,Car,5.0,18,70,1.0
4,C007,Nampally,Ameerpet,Walking,4.0,50,0,0.0
5,C007,Nampally,Ameerpet,Bicycle,4.0,17,0,0.0
6,C007,Nampally,Ameerpet,Public Transport,4.0,28,20,0.4
7,C007,Nampally,Ameerpet,Car,4.0,13,60,0.8
8,C008,Mehdipatnam,Charminar,Walking,6.0,76,0,0.0
9,C008,Mehdipatnam,Charminar,Bicycle,6.0,25,0,0.0
10,C008,Mehdipatnam,Charminar,Public Transport,6.0,42,25,0.6
11,C008,Mehdipatnam,Charminar,Car,6.0,21,90,1.2
12,C009,Mehdipatnam,Banjara Hills,Walking,4.0,51,0,0.0
13,C009,Mehdipatnam,Banjara Hills,Bicycle,4.0,17,0,0.0
14,C009,Mehdipatnam,Banjara Hills,Public Transport,4.0,30,20,0.4
15,C009,Mehdipatnam,Banjara Hills,Car,4.0,15,70,0.8
16,C010,Ameerpet,Begumpet,Walking,3.5,44,0,0.0
17,C010,Ameerpet,Begumpet,Bicycle,3.5,15,0,0.0
18,C010,Ameerpet,Begumpet,Public Transport,3.5,25,15,0.3
19,C010,Ameerpet,Begumpet,Car,3.5,12,55,0.6

In [35]:
print('Shape: ',df2.shape)

Shape:  (20, 8)

In [36]:
print('Unique Connections: ',df2['connection_id'].nunique())

Unique Connections:  5

In [37]:
df3 = pd.DataFrame({
    "connection_id": [
        "C011", "C011", "C011", "C011",
        "C012", "C012", "C012", "C012",
        "C013", "C013", "C013", "C013",
        "C014", "C014", "C014", "C014",
        "C015", "C015", "C015", "C015"
    ],
    "source": [
        "Ameerpet", "Ameerpet", "Ameerpet", "Ameerpet",
        "Begumpet", "Begumpet", "Begumpet", "Begumpet",
        "Begumpet", "Begumpet", "Begumpet", "Begumpet",
        "Banjara Hills", "Banjara Hills", "Banjara Hills", "Banjara Hills",
        "Jubilee Hills", "Jubilee Hills", "Jubilee Hills", "Jubilee Hills"
    ],
    "destination": [
        "Banjara Hills", "Banjara Hills", "Banjara Hills", "Banjara Hills",
        "Secunderabad", "Secunderabad", "Secunderabad", "Secunderabad",
        "Jubilee Hills", "Jubilee Hills", "Jubilee Hills", "Jubilee Hills",
        "Jubilee Hills", "Jubilee Hills", "Jubilee Hills", "Jubilee Hills",
        "HITEC City", "HITEC City", "HITEC City", "HITEC City"
    ],
    "mode": [
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car"
    ],
    "distance_km": [
        4.0, 4.0, 4.0, 4.0,
        4.0, 4.0, 4.0, 4.0,
        5.0, 5.0, 5.0, 5.0,
        3.0, 3.0, 3.0, 3.0,
        6.0, 6.0, 6.0, 6.0
    ],
    "duration_min": [
        51, 17, 29, 14,
        51, 17, 29, 14,
        64, 21, 35, 18,
        38, 13, 22, 11,
        76, 25, 42, 19
    ],
    "cost_inr": [
        0, 0, 20, 65,
        0, 0, 15, 55,
        0, 0, 20, 70,
        0, 0, 15, 50,
        0, 0, 25, 90
    ],
    "co2_kg": [
        0.0, 0.0, 0.4, 0.8,
        0.0, 0.0, 0.4, 0.8,
        0.0, 0.0, 0.5, 1.0,
        0.0, 0.0, 0.3, 0.6,
        0.0, 0.0, 0.6, 1.2
    ]
})

df3

,connection_id,source,destination,mode,distance_km,duration_min,cost_inr,co2_kg
0,C011,Ameerpet,Banjara Hills,Walking,4.0,51,0,0.0
1,C011,Ameerpet,Banjara Hills,Bicycle,4.0,17,0,0.0
2,C011,Ameerpet,Banjara Hills,Public Transport,4.0,29,20,0.4
3,C011,Ameerpet,Banjara Hills,Car,4.0,14,65,0.8
4,C012,Begumpet,Secunderabad,Walking,4.0,51,0,0.0
5,C012,Begumpet,Secunderabad,Bicycle,4.0,17,0,0.0
6,C012,Begumpet,Secunderabad,Public Transport,4.0,29,15,0.4
7,C012,Begumpet,Secunderabad,Car,4.0,14,55,0.8
8,C013,Begumpet,Jubilee Hills,Walking,5.0,64,0,0.0
9,C013,Begumpet,Jubilee Hills,Bicycle,5.0,21,0,0.0
10,C013,Begumpet,Jubilee Hills,Public Transport,5.0,35,20,0.5
11,C013,Begumpet,Jubilee Hills,Car,5.0,18,70,1.0
12,C014,Banjara Hills,Jubilee Hills,Walking,3.0,38,0,0.0
13,C014,Banjara Hills,Jubilee Hills,Bicycle,3.0,13,0,0.0
14,C014,Banjara Hills,Jubilee Hills,Public Transport,3.0,22,15,0.3
15,C014,Banjara Hills,Jubilee Hills,Car,3.0,11,50,0.6
16,C015,Jubilee Hills,HITEC City,Walking,6.0,76,0,0.0
17,C015,Jubilee Hills,HITEC City,Bicycle,6.0,25,0,0.0
18,C015,Jubilee Hills,HITEC City,Public Transport,6.0,42,25,0.6
19,C015,Jubilee Hills,HITEC City,Car,6.0,19,90,1.2

In [38]:
print('Shape: ',df3.shape)

Shape:  (20, 8)

In [39]:
print('Unique Connections: ',df3['connection_id'].nunique())

Unique Connections:  5

In [40]:
df4 = pd.DataFrame({
    "connection_id": [
        "C016", "C016", "C016", "C016",
        "C017", "C017", "C017", "C017",
        "C018", "C018", "C018", "C018",
        "C019", "C019", "C019", "C019",
        "C020", "C020", "C020", "C020"
    ],
    "source": [
        "Jubilee Hills", "Jubilee Hills", "Jubilee Hills", "Jubilee Hills",
        "HITEC City", "HITEC City", "HITEC City", "HITEC City",
        "HITEC City", "HITEC City", "HITEC City", "HITEC City",
        "Ameerpet", "Ameerpet", "Ameerpet", "Ameerpet",
        "Kukatpally", "Kukatpally", "Kukatpally", "Kukatpally"
    ],
    "destination": [
        "Gachibowli", "Gachibowli", "Gachibowli", "Gachibowli",
        "Gachibowli", "Gachibowli", "Gachibowli", "Gachibowli",
        "Miyapur", "Miyapur", "Miyapur", "Miyapur",
        "Kukatpally", "Kukatpally", "Kukatpally", "Kukatpally",
        "Miyapur", "Miyapur", "Miyapur", "Miyapur"
    ],
    "mode": [
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car"
    ],
    "distance_km": [
        5.0, 5.0, 5.0, 5.0,
        3.5, 3.5, 3.5, 3.5,
        9.0, 9.0, 9.0, 9.0,
        6.0, 6.0, 6.0, 6.0,
        5.0, 5.0, 5.0, 5.0
    ],
    "duration_min": [
        64, 21, 35, 18,
        45, 15, 25, 12,
        114, 38, 52, 25,
        76, 25, 40, 20,
        64, 21, 35, 17
    ],
    "cost_inr": [
        0, 0, 20, 75,
        0, 0, 20, 60,
        0, 0, 30, 130,
        0, 0, 25, 100,
        0, 0, 20, 70
    ],
    "co2_kg": [
        0.0, 0.0, 0.5, 1.0,
        0.0, 0.0, 0.4, 0.7,
        0.0, 0.0, 0.8, 1.8,
        0.0, 0.0, 0.6, 1.2,
        0.0, 0.0, 0.5, 0.9
    ]
})

df4

,connection_id,source,destination,mode,distance_km,duration_min,cost_inr,co2_kg
0,C016,Jubilee Hills,Gachibowli,Walking,5.0,64,0,0.0
1,C016,Jubilee Hills,Gachibowli,Bicycle,5.0,21,0,0.0
2,C016,Jubilee Hills,Gachibowli,Public Transport,5.0,35,20,0.5
3,C016,Jubilee Hills,Gachibowli,Car,5.0,18,75,1.0
4,C017,HITEC City,Gachibowli,Walking,3.5,45,0,0.0
5,C017,HITEC City,Gachibowli,Bicycle,3.5,15,0,0.0
6,C017,HITEC City,Gachibowli,Public Transport,3.5,25,20,0.4
7,C017,HITEC City,Gachibowli,Car,3.5,12,60,0.7
8,C018,HITEC City,Miyapur,Walking,9.0,114,0,0.0
9,C018,HITEC City,Miyapur,Bicycle,9.0,38,0,0.0
10,C018,HITEC City,Miyapur,Public Transport,9.0,52,30,0.8
11,C018,HITEC City,Miyapur,Car,9.0,25,130,1.8
12,C019,Ameerpet,Kukatpally,Walking,6.0,76,0,0.0
13,C019,Ameerpet,Kukatpally,Bicycle,6.0,25,0,0.0
14,C019,Ameerpet,Kukatpally,Public Transport,6.0,40,25,0.6
15,C019,Ameerpet,Kukatpally,Car,6.0,20,100,1.2
16,C020,Kukatpally,Miyapur,Walking,5.0,64,0,0.0
17,C020,Kukatpally,Miyapur,Bicycle,5.0,21,0,0.0
18,C020,Kukatpally,Miyapur,Public Transport,5.0,35,20,0.5
19,C020,Kukatpally,Miyapur,Car,5.0,17,70,0.9

In [41]:
print('Shape: ',df4.shape)

Shape:  (20, 8)

In [42]:
print('Unique Connections: ',df4['connection_id'].nunique())

Unique Connections:  5

In [43]:
df5 = pd.DataFrame({
    "connection_id": [
        "C021", "C021", "C021", "C021",
        "C022", "C022", "C022", "C022",
        "C023", "C023", "C023", "C023",
        "C024", "C024", "C024", "C024",
        "C025", "C025", "C025", "C025"
    ],
    "source": [
        "Begumpet", "Begumpet", "Begumpet", "Begumpet",
        "Paradise", "Paradise", "Paradise", "Paradise",
        "Koti", "Koti", "Koti", "Koti",
        "Dilsukhnagar", "Dilsukhnagar", "Dilsukhnagar", "Dilsukhnagar",
        "LB Nagar", "LB Nagar", "LB Nagar", "LB Nagar"
    ],
    "destination": [
        "Paradise", "Paradise", "Paradise", "Paradise",
        "Secunderabad", "Secunderabad", "Secunderabad", "Secunderabad",
        "Dilsukhnagar", "Dilsukhnagar", "Dilsukhnagar", "Dilsukhnagar",
        "LB Nagar", "LB Nagar", "LB Nagar", "LB Nagar",
        "Uppal", "Uppal", "Uppal", "Uppal"
    ],
    "mode": [
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car"
    ],
    "distance_km": [
        2.5, 2.5, 2.5, 2.5,
        2.0, 2.0, 2.0, 2.0,
        5.5, 5.5, 5.5, 5.5,
        3.0, 3.0, 3.0, 3.0,
        6.0, 6.0, 6.0, 6.0
    ],
    "duration_min": [
        32, 11, 18, 9,
        26, 9, 16, 8,
        70, 23, 38, 19,
        38, 13, 22, 11,
        76, 25, 40, 20
    ],
    "cost_inr": [
        0, 0, 15, 40,
        0, 0, 15, 35,
        0, 0, 20, 75,
        0, 0, 15, 45,
        0, 0, 25, 85
    ],
    "co2_kg": [
        0.0, 0.0, 0.3, 0.6,
        0.0, 0.0, 0.2, 0.4,
        0.0, 0.0, 0.6, 1.2,
        0.0, 0.0, 0.3, 0.6,
        0.0, 0.0, 0.6, 1.3
    ]
})

df5

,connection_id,source,destination,mode,distance_km,duration_min,cost_inr,co2_kg
0,C021,Begumpet,Paradise,Walking,2.5,32,0,0.0
1,C021,Begumpet,Paradise,Bicycle,2.5,11,0,0.0
2,C021,Begumpet,Paradise,Public Transport,2.5,18,15,0.3
3,C021,Begumpet,Paradise,Car,2.5,9,40,0.6
4,C022,Paradise,Secunderabad,Walking,2.0,26,0,0.0
5,C022,Paradise,Secunderabad,Bicycle,2.0,9,0,0.0
6,C022,Paradise,Secunderabad,Public Transport,2.0,16,15,0.2
7,C022,Paradise,Secunderabad,Car,2.0,8,35,0.4
8,C023,Koti,Dilsukhnagar,Walking,5.5,70,0,0.0
9,C023,Koti,Dilsukhnagar,Bicycle,5.5,23,0,0.0
10,C023,Koti,Dilsukhnagar,Public Transport,5.5,38,20,0.6
11,C023,Koti,Dilsukhnagar,Car,5.5,19,75,1.2
12,C024,Dilsukhnagar,LB Nagar,Walking,3.0,38,0,0.0
13,C024,Dilsukhnagar,LB Nagar,Bicycle,3.0,13,0,0.0
14,C024,Dilsukhnagar,LB Nagar,Public Transport,3.0,22,15,0.3
15,C024,Dilsukhnagar,LB Nagar,Car,3.0,11,45,0.6
16,C025,LB Nagar,Uppal,Walking,6.0,76,0,0.0
17,C025,LB Nagar,Uppal,Bicycle,6.0,25,0,0.0
18,C025,LB Nagar,Uppal,Public Transport,6.0,40,25,0.6
19,C025,LB Nagar,Uppal,Car,6.0,20,85,1.3

In [44]:
print('Shape: ',df5.shape)

Shape:  (20, 8)

In [45]:
print('Unique Connections: ',df5['connection_id'].nunique())

Unique Connections:  5

In [46]:
df6 = pd.DataFrame({
    "connection_id": [
        "C026", "C026", "C026", "C026",
        "C027", "C027", "C027", "C027",
        "C028", "C028", "C028", "C028",
        "C029", "C029", "C029", "C029",
        "C030", "C030", "C030", "C030"
    ],
    "source": [
        "Uppal", "Uppal", "Uppal", "Uppal",
        "Secunderabad", "Secunderabad", "Secunderabad", "Secunderabad",
        "Banjara Hills", "Banjara Hills", "Banjara Hills", "Banjara Hills",
        "Tolichowki", "Tolichowki", "Tolichowki", "Tolichowki",
        "HITEC City", "HITEC City", "HITEC City", "HITEC City"
    ],
    "destination": [
        "Koti", "Koti", "Koti", "Koti",
        "Paradise", "Paradise", "Paradise", "Paradise",
        "Mehdipatnam", "Mehdipatnam", "Mehdipatnam", "Mehdipatnam",
        "Gachibowli", "Gachibowli", "Gachibowli", "Gachibowli",
        "Kukatpally", "Kukatpally", "Kukatpally", "Kukatpally"
    ],
    "mode": [
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car",
        "Walking", "Bicycle", "Public Transport", "Car"
    ],
    "distance_km": [
        7.0, 7.0, 7.0, 7.0,
        2.0, 2.0, 2.0, 2.0,
        4.0, 4.0, 4.0, 4.0,
        5.0, 5.0, 5.0, 5.0,
        7.0, 7.0, 7.0, 7.0
    ],
    "duration_min": [
        88, 29, 48, 24,
        26, 9, 16, 8,
        51, 17, 29, 14,
        64, 21, 35, 17,
        89, 30, 50, 23
    ],
    "cost_inr": [
        0, 0, 25, 95,
        0, 0, 15, 35,
        0, 0, 20, 65,
        0, 0, 25, 85,
        0, 0, 25, 100
    ],
    "co2_kg": [
        0.0, 0.0, 0.7, 1.4,
        0.0, 0.0, 0.2, 0.4,
        0.0, 0.0, 0.4, 0.8,
        0.0, 0.0, 0.5, 1.0,
        0.0, 0.0, 0.7, 1.4
    ]
})

df6

,connection_id,source,destination,mode,distance_km,duration_min,cost_inr,co2_kg
0,C026,Uppal,Koti,Walking,7.0,88,0,0.0
1,C026,Uppal,Koti,Bicycle,7.0,29,0,0.0
2,C026,Uppal,Koti,Public Transport,7.0,48,25,0.7
3,C026,Uppal,Koti,Car,7.0,24,95,1.4
4,C027,Secunderabad,Paradise,Walking,2.0,26,0,0.0
5,C027,Secunderabad,Paradise,Bicycle,2.0,9,0,0.0
6,C027,Secunderabad,Paradise,Public Transport,2.0,16,15,0.2
7,C027,Secunderabad,Paradise,Car,2.0,8,35,0.4
8,C028,Banjara Hills,Mehdipatnam,Walking,4.0,51,0,0.0
9,C028,Banjara Hills,Mehdipatnam,Bicycle,4.0,17,0,0.0
10,C028,Banjara Hills,Mehdipatnam,Public Transport,4.0,29,20,0.4
11,C028,Banjara Hills,Mehdipatnam,Car,4.0,14,65,0.8
12,C029,Tolichowki,Gachibowli,Walking,5.0,64,0,0.0
13,C029,Tolichowki,Gachibowli,Bicycle,5.0,21,0,0.0
14,C029,Tolichowki,Gachibowli,Public Transport,5.0,35,25,0.5
15,C029,Tolichowki,Gachibowli,Car,5.0,17,85,1.0
16,C030,HITEC City,Kukatpally,Walking,7.0,89,0,0.0
17,C030,HITEC City,Kukatpally,Bicycle,7.0,30,0,0.0
18,C030,HITEC City,Kukatpally,Public Transport,7.0,50,25,0.7
19,C030,HITEC City,Kukatpally,Car,7.0,23,100,1.4

In [47]:
print('Shape: ',df6.shape)

Shape:  (20, 8)

In [48]:
print('Unique Connections: ',df6['connection_id'].nunique())

Unique Connections:  5

In [49]:
df=pd.concat([df1,df2,df3,df4,df5,df6],ignore_index=True)
df

,connection_id,source,destination,mode,distance_km,duration_min,cost_inr,co2_kg
0,C001,Koti,Abids,Walking,2.0,26,0,0.0
1,C001,Koti,Abids,Bicycle,2.0,9,0,0.0
2,C001,Koti,Abids,Public Transport,2.0,16,15,0.2
3,C001,Koti,Abids,Car,2.0,8,35,0.5
4,C002,Koti,Nampally,Walking,3.0,38,0,0.0
...,...,...,...,...,...,...,...,...
115,C029,Tolichowki,Gachibowli,Car,5.0,17,85,1.0
116,C030,HITEC City,Kukatpally,Walking,7.0,89,0,0.0
117,C030,HITEC City,Kukatpally,Bicycle,7.0,30,0,0.0
118,C030,HITEC City,Kukatpally,Public Transport,7.0,50,25,0.7
119,C030,HITEC City,Kukatpally,Car,7.0,23,100,1.4

In [50]:
print('Dataset Shape: ',df.shape)

Dataset Shape:  (120, 8)

In [51]:
print('Column Names: ')
print(df.columns.tolist())

Column Names:
['connection_id', 'source', 'destination', 'mode', 'distance_km', 'duration_min', 'cost_inr', 'co2_kg']

In [52]:
print('Unique Connections: ',df['connection_id'].nunique())

Unique Connections:  30

In [53]:
print('Transportation Modes: ')
print(df['mode'].unique())

Transportation Modes:
<ArrowStringArray>
['Walking', 'Bicycle', 'Public Transport', 'Car']
Length: 4, dtype: str

In [54]:
print('Number of Rows per Mode: ')
print(df['mode'].value_counts())

Number of Rows per Mode:
mode
Walking             30
Bicycle             30
Public Transport    30
Car                 30
Name: count, dtype: int64

In [55]:
print('Duplicate Rows: ',df.duplicated().sum())

Duplicate Rows:  0

In [56]:
print('Missing values: ',df.isnull().sum())

Missing values:  connection_id    0
source           0
destination      0
mode             0
distance_km      0
duration_min     0
cost_inr         0
co2_kg           0
dtype: int64

In [57]:
print('Unique Locations: ',pd.unique(df[['source','destination']].values.ravel()))

Unique Locations:  ['Koti' 'Abids' 'Nampally' 'Charminar' 'Mehdipatnam' 'Ameerpet'
 'Banjara Hills' 'Begumpet' 'Secunderabad' 'Jubilee Hills' 'HITEC City'
 'Gachibowli' 'Miyapur' 'Kukatpally' 'Paradise' 'Dilsukhnagar' 'LB Nagar'
 'Uppal' 'Tolichowki']

In [58]:
df.to_csv('multimodal_mobility_network.csv',index=False)
print('Dataset saved successfully')

Dataset saved successfully